import PDFDocument from 'pdfkit';

class ExportService {
    /**
     * Generate Markdown content for a review
     */
    generateMarkdown(review: any): string {
        const data = typeof review.result === 'string' ? JSON.parse(review.result) : review.result;
        const date = new Date(review.created_at).toLocaleDateString();
        
        let md = `# 🤖 AI Code Review Report\n\n`;
        md += `**Date:** ${date}\n`;
        md += `**Repository:** ${review.repository_name || 'Manual Upload'}\n`;
        md += `**Language:** ${review.language.toUpperCase()}\n`;
        md += `**Analysis Type:** ${review.analysis_type.replace('-', ' ').toUpperCase()}\n`;
        md += `**Status:** ${review.success ? '✅ Success' : '❌ Failed'}\n\n`;

        if (data) {
            if (data.summary) {
                md += `## 📋 Summary\n${data.summary}\n\n`;
            }

            if (data.overallScore !== undefined) {
                md += `## 📊 Overall Score: ${data.overallScore}/100\n\n`;
            }

            const issues = data.issues || data.smells || data.vulnerabilities || [];
            if (issues.length > 0) {
                md += `## ⚠️ Issues Found (${issues.length})\n\n`;
                issues.forEach((issue: any, index: number) => {
                    const severityIco = issue.severity === 'high' ? '🔴' : issue.severity === 'medium' ? '🟠' : '🟢';
                    md += `### ${index + 1}. ${severityIco} ${issue.type || 'Issue'}\n`;
                    md += `**Severity:** ${issue.severity?.toUpperCase()}\n`;
                    if (issue.line) md += `**Line:** ${issue.line}\n`;
                    md += `**Description:** ${issue.description}\n`;
                    if (issue.why) md += `**Why it matters:** ${issue.why}\n`;
                    if (issue.suggestion || issue.fix) md += `**Recommendation:** ${issue.suggestion || issue.fix}\n`;
                    md += `\n`;
                });
            }

            if (data.strengths && data.strengths.length > 0) {
                md += `## ✨ Strengths\n`;
                data.strengths.forEach((s: string) => md += `* ${s}\n`);
                md += `\n`;
            }
        }

        md += `---\n*Generated by Code Review Bot* 🚀`;
        return md;
    }

    /**
     * Generate PDF stream for a review
     */
    generatePDF(review: any, res: any) {
        const doc = new PDFDocument({ margin: 50 });
        const data = typeof review.result === 'string' ? JSON.parse(review.result) : review.result;
        const date = new Date(review.created_at).toLocaleDateString();

        // Title
        doc.fillColor('#2563eb').fontSize(24).text('AI Code Review Report', { align: 'center' });
        doc.moveDown();

        // Meta Info
        doc.fillColor('#4b5563').fontSize(12);
        doc.text(`Date: ${date}`);
        doc.text(`Repository: ${review.repository_name || 'Manual Upload'}`);
        doc.text(`Language: ${review.language.toUpperCase()}`);
        doc.text(`Analysis: ${review.analysis_type.replace('-', ' ').toUpperCase()}`);
        doc.moveDown();
        doc.rect(50, doc.y, 500, 1).fill('#e5e7eb');
        doc.moveDown();

        if (data) {
            // Score
            if (data.overallScore !== undefined) {
                doc.fillColor('#111827').fontSize(18).text(`Overall Score: ${data.overallScore}/100`);
                doc.moveDown();
            }

            // Summary
            if (data.summary) {
                doc.fillColor('#374151').fontSize(14).text('Summary', { underline: true });
                doc.fontSize(11).text(data.summary);
                doc.moveDown();
            }

            // Issues
            const issues = data.issues || data.smells || data.vulnerabilities || [];
            if (issues.length > 0) {
                doc.fillColor('#ef4444').fontSize(14).text(`Issues Found (${issues.length})`, { underline: true });
                doc.moveDown(0.5);

                issues.forEach((issue: any, i: number) => {
                    doc.fillColor('#111827').fontSize(12).text(`${i + 1}. ${issue.type || 'Observation'}`);
                    doc.fillColor('#4b5563').fontSize(10);
                    doc.text(`Severity: ${issue.severity?.toUpperCase()}`);
                    if (issue.line) doc.text(`Line: ${issue.line}`);
                    doc.fillColor('#111827').text(`Description: ${issue.description}`);
                    if (issue.suggestion || issue.fix) {
                        doc.fillColor('#10b981').text(`Recommendation: ${issue.suggestion || issue.fix}`);
                    }
                    doc.moveDown();
                });
            }
        }

        doc.fontSize(10).fillColor('#9ca3af').text('Generated by Code Review Bot', { align: 'center', baseline: 'bottom' });

        doc.pipe(res);
        doc.end();
    }
}

export const exportService = new ExportService();
export default exportService;
